apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: myapp
    tier: myapp
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
        tier: myapp
    spec:
      containers:
      - image: anilpivotal/my-image:myapp-v1
        name: myapp
        ports:
        - containerPort: 8080
        imagePullPolicy: Always        
        name: myapp
